name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
#  sdk: ^3.10.4   이상 모듈까지 전부 허용 (3.10.4 이상 but 3.10.4 미만 불가)
  sdk: '>=3.0.0 <4.0.0'   # 범위 지정 허용 (3.0.0 이상 4.0.0 미만)


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  dio: ^5.4.3
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  go_router: ^14.0.0
  web: ^1.1.1
  webview_flutter: ^4.4.4
  google_fonts: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ # assets 폴더 내부 images 폴더 내의 모든 파일 사용할 것이다.
    - .env.development
    - .env.product
    - .env.local

  # assets 추가 시 pub get으로 반드시 추가된 세팅 반영하도록 한다.
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
